#!/usr/bin/env zsh

(git ls-files test; git ls-files '*.cabal'; git ls-files 'flake.*') | \
  entr -r \
    nix develop -c \
      ghcid \
        --warnings \
        "--command=cabal repl lib:quasar-network" \
        "--test=:! \
          zsh -c 'print -P %F{yellow}Cleaning repository to ensure template haskell is run%f' && \
          cabal clean && \
          cabal test --test-show-details=direct --ghc-option -fdiagnostics-color=always && \
          cabal build --ghc-option -fdiagnostics-color=always && \
          zsh -c 'print -P %F{green}Build and tests passed%f' \
        "
